import {StyleSheet, Platform} from 'react-native';
import {
  widthPercentageToDP as wp,
  heightPercentageToDP as hp,
} from 'react-native-responsive-screen';

export const styles = StyleSheet.create({
  safeArea: {flex: 1, backgroundColor: '#f5f5f5'},
  container: {
    flex: 1,
    paddingHorizontal: Platform.select({ios: wp(6), android: wp(5)}),
    paddingBottom: Platform.select({ios: hp(7), android: hp(10)}),
  },
  tabWrapper: {
    backgroundColor: '#ffffff',
    borderRadius: wp(3),
    marginVertical: hp(2),
    padding: hp(1),
  },
  tabContainer: {paddingHorizontal: wp(2), alignItems: 'center'},
  tabButton: {
    paddingVertical: hp(1.2),
    paddingHorizontal: wp(4),
    marginRight: wp(1.5),
    borderRadius: wp(2),
    backgroundColor: '#f8f9fa',
    alignItems: 'center',
    justifyContent: 'center',
  },
  activeTabButton: {backgroundColor: '#FF0080'},
  tabText: {fontSize: wp(4), fontWeight: '600', color: '#333333'},
  activeTabText: {color: '#ffffff', fontWeight: '700'},
  listContainer: {paddingBottom: hp(2)},
  noOrdersContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: hp(10),
  },
  noOrdersText: {
    fontSize: wp(5),
    fontWeight: '600',
    color: '#333333',
    textAlign: 'center',
    marginBottom: hp(2),
  },
  cardContainer: {marginBottom: hp(1.5)},
  card: {
    backgroundColor: 'white',
    borderRadius: wp(3),
    padding: wp(4),
    flexDirection: 'column',
  },
  cardContent: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
  },
  detailsContainer: {flex: 1},
  orderHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  orderNumber: {fontSize: wp(4.5), fontWeight: 'bold', color: '#000000'},
  status: {fontSize: wp(4.2), fontWeight: '500', marginBottom: hp(0.5)},
  dateText: {fontSize: wp(3.8), marginBottom: hp(0.5), color: '#6c757d'},
  priceText: {fontSize: wp(4.5), fontWeight: 'bold'},
  buttonRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: hp(0.5),
  },
  paymentStatus: {
    backgroundColor: '#00A19D',
    paddingVertical: wp(1.5),
    paddingHorizontal: wp(5),
    borderRadius: wp(1),
  },
  paymentStatusText: {color: 'white', fontSize: wp(3.5), fontWeight: 'bold'},
  feedbackButton: {
    backgroundColor: '#FF0080',
    paddingVertical: wp(1.5),
    paddingHorizontal: wp(5),
    borderRadius: wp(1),
  },
  feedbackButtonText: {color: 'white', fontSize: wp(3.5), fontWeight: 'bold'},
  ratingButton: {
    backgroundColor: '#00A19D',
    paddingVertical: wp(2),
    paddingHorizontal: wp(5),
    borderRadius: wp(2),
    alignSelf: 'flex-start',
    marginTop: hp(0.5),
  },
  ratingButtonText: {color: 'white', fontSize: wp(3.8), fontWeight: '600'},
  trackingButton: {
    backgroundColor: '#5C6BC0',
    paddingVertical: wp(2),
    paddingHorizontal: wp(5),
    borderRadius: wp(2),
    alignSelf: 'flex-start',
    marginTop: hp(0.5),
  },
  trackingButtonText: {color: 'white', fontSize: wp(3.8), fontWeight: '600'},
  menuButton: {},
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.3)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalContent: {
    backgroundColor: 'white',
    borderRadius: wp(4),
    padding: wp(5),
    width: wp(85),
    maxHeight: hp(70),
  },
  statusModalContent: {borderRadius: wp(4), padding: wp(5), width: wp(85)},
  trackingModalContent: {
    borderRadius: wp(4),
    padding: wp(5),
    width: wp(85),
    alignItems: 'center',
  },
  cancelModalContent: {
    borderRadius: wp(4),
    padding: wp(5),
    width: wp(85),
    alignItems: 'center',
  },
  modalTitle: {
    fontSize: wp(5),
    fontWeight: 'bold',
    marginBottom: hp(2),
    textAlign: 'center',
    color: '#333',
  },
  itemsContainer: {flexGrow: 0, marginBottom: hp(2)},
  itemCard: {
    backgroundColor: 'rgba(0, 161, 157, 0.1)',
    borderRadius: wp(3),
    padding: wp(4),
    marginBottom: hp(1.5),
  },
  itemTitle: {
    fontSize: wp(5),
    fontWeight: 'bold',
    marginBottom: hp(1),
    color: '#333',
  },
  itemDetailRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: hp(0.5),
  },
  itemDetailLabel: {fontSize: wp(3.8), color: '#6c757d'},
  itemDetailValue: {fontSize: wp(3.8), fontWeight: '500', color: '#333'},
  statusCirclesContainer: {
    marginBottom: hp(2),
    justifyContent: 'center',
    alignItems: 'center',
  },
  statusCircleWrapper: {
    alignItems: 'center',
    marginHorizontal: wp(3),
    marginVertical: hp(1),
    flexDirection: 'row',
    gap: wp(2),
  },
  statusCircle: {
    width: wp(3),
    height: wp(3),
    borderRadius: wp(4),
    borderWidth: 2,
  },
  statusCircleText: {fontSize: wp(4), color: '#333'},
  trackingStatusText: {
    fontSize: wp(4.5),
    fontWeight: '500',
    marginBottom: hp(2),
    textAlign: 'center',
  },
  cancelButton: {
    backgroundColor: '#FF0000',
    paddingVertical: wp(3),
    width: wp(30),
    borderRadius: wp(3),
    alignSelf: 'center',
    marginBottom: hp(2),
    alignItems: 'center',
  },
  cancelButtonText: {color: 'white', fontSize: wp(4.2), fontWeight: 'bold'},
  disputeButton: {
    backgroundColor: '#FF0080',
    paddingVertical: wp(3),
    width: wp(40),
    borderRadius: wp(3),
    alignSelf: 'center',
    alignItems: 'center',
  },
  disputeButtonText: {color: 'white', fontSize: wp(4.2), fontWeight: 'bold'},
  closeButton: {
    backgroundColor: '#00A19D',
    paddingVertical: wp(3),
    width: wp(30),
    borderRadius: wp(3),
    alignSelf: 'center',
    marginBottom: hp(2),
    alignItems: 'center',
  },
  closeButtonText: {color: 'white', fontSize: wp(4.2), fontWeight: 'bold'},
  footerContainer: {padding: hp(2), alignItems: 'center'},
  footerText: {fontSize: wp(4), color: '#333', marginBottom: hp(1)},
  retryButton: {
    backgroundColor: '#00A19D',
    paddingVertical: hp(1.5),
    paddingHorizontal: wp(5),
    borderRadius: wp(2),
  },
  retryButtonText: {color: 'white', fontSize: wp(4), fontWeight: '600'},
});
