import {StyleSheet, Platform} from 'react-native';
import {
  widthPercentageToDP as wp,
  heightPercentageToDP as hp,
} from 'react-native-responsive-screen';

export const styles = StyleSheet.create({
  safeArea: {flex: 1, backgroundColor: '#f0f4f8'},
  container: {flex: 1, paddingHorizontal: wp(5)},
  profileSection: {alignItems: 'center', marginTop: hp(2), marginBottom: hp(2)},
  profileImagePlaceholder: {
    width: wp(30),
    height: wp(30),
    borderRadius: wp(15),
    backgroundColor: '#ddd',
    justifyContent: 'center',
    alignItems: 'center',
  },
  profileImageText: {fontSize: wp(10), fontWeight: 'bold'},
  profileName: {fontSize: wp(5), fontWeight: 'bold', marginTop: hp(1)},
  profileLocation: {fontSize: wp(3.5), color: '#666', marginBottom: hp(1)},
  chatButton: {
    flexDirection: 'row',
    backgroundColor: '#00cec9',
    paddingVertical: hp(1),
    paddingHorizontal: wp(3),
    borderRadius: 8,
    alignItems: 'center',
  },
  disabledChatButton: {backgroundColor: '#cccccc', opacity: 0.6},
  chatButtonText: {fontSize: wp(4), color: '#fff', marginLeft: wp(1)},
  section: {marginTop: hp(2)},
  sectionTitle: {fontSize: wp(4.5), fontWeight: 'bold', marginBottom: hp(1)},
  reviewContent: {paddingRight: wp(5)},
  reviewCard: {
    padding: wp(3),
    borderRadius: 15,
    marginBottom: hp(1.5),
    backgroundColor: '#fff',
  },
  reviewText: {fontSize: wp(3.5), marginBottom: hp(1)},
  noReviewsText: {
    fontSize: wp(3.5),
    textAlign: 'center',
    marginVertical: hp(2),
  },
  serviceList: {marginTop: hp(1)},
  serviceContent: {paddingRight: wp(5)},
  serviceCard: {
    backgroundColor: '#fff',
    borderRadius: 15,
    padding: wp(2),
    marginRight: wp(2),
    width: wp(25),
    alignItems: 'center',
  },
  serviceName: {fontSize: wp(3.5), marginBottom: hp(1)},
  serviceInfo: {alignItems: 'center'},
  servicePrice: {
    fontSize: wp(3.5),
    color: '#000',
    fontWeight: 'bold',
    marginBottom: hp(0.5),
  },
  ratingContainer: {flexDirection: 'row', alignItems: 'center'},
  ratingText: {fontSize: wp(3), color: '#666', marginLeft: wp(1)},
  reviewSection: {alignItems: 'center', marginTop: hp(2), marginBottom: hp(2)},
  ratingValue: {fontSize: wp(6), fontWeight: 'bold', marginRight: wp(1)},
  reviewsText: {fontSize: wp(3.5), color: '#666'},
  payButton: {
    position: 'absolute',
    bottom: Platform.select({ios: hp(2), android: hp(2)}),
    left: Platform.select({ios: wp(6), android: wp(5)}),
    right: Platform.select({ios: wp(6), android: wp(5)}),
    marginBottom: hp(2),
  },
  errorText: {
    fontSize: wp(4),
    textAlign: 'center',
    marginVertical: hp(2),
    color: 'red',
  },
  loadingText: {fontSize: wp(4), textAlign: 'center', marginTop: hp(10)},
});
